# Site settings
title: Véro + John
email: youremailaddress@gmail.com
description: Wedding Site of Véronique Nobert and John Ho
baseurl: "" #"/spectral-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

#Homepage Settings
landing_title: Véro + John
landing_description: Tai Hang, Hong Kong <br><br> March 31, 2018
landing_button: RSVP
landing_button_url: "#cta"
banner_image: "assets/images/banner.jpg" # the path of banner image; doesn't really work at the moment

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/ohjho/toiplusmoi
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:
soundcloud_url: https://soundcloud.com/ohjho
whatsapp_url: https://api.whatsapp.com/send?phone=85266265090

# Build settings
markdown: kramdown
